CREATE TABLE `movies` (
	`id` bigint unsigned AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`overview` text NOT NULL,
	`release_date` date NOT NULL,
	`runtime` int,
	`tmdb_id` varchar(255),
	`imdb_id` varchar(255),
	`adult` tinyint NOT NULL DEFAULT 1,
	`site` varchar(255),
	`original_language` varchar(255),
	`budget` bigint,
	`revenue` bigint,
	`vote_average` float,
	`vote_count` bigint,
	`tagline` varchar(255),
	`status` varchar(255) NOT NULL DEFAULT 'Draft',
	`trailer_id` bigint unsigned,
	`logo_id` bigint unsigned,
	`backdrop_id` bigint unsigned,
	`poster_id` bigint unsigned,
	`created_at` timestamp DEFAULT (now()),
	`updated_at` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `movies_id` PRIMARY KEY(`id`)
);
